name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  generate-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      -
        name: Run generation
        run: go generate ./...
      -
        name: Check for differences
        run: git diff --exit-code

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
      -
        name: Test
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
      -
        name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage.out

  codecov:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v4
      -
        name: Download Coverage Artifact
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
      -
        name: Validate codecov.yml
        run: cat .codecov.yml | curl --data-binary @- https://codecov.io/validate
      -
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
